### Упражнение 1

* Скачайте с портала Открытых Данных производственный календарь России: https://data.gov.ru/opendata/7708660670-proizvcalendar
* На его основе определите соответствующий календарь в Pandas: `RussianBusinessCalendar(AbstractHolidayCalendar)`
* С помощью полученного в пункте выше календаря и модуля `pd.offsets` создайте DataFrame one-hot календарных признаков:
    * День недели
    * Месяц
    * Выходной день
    * Праздничный день
    * Предпраздничный рабочий день
    * Последний день месяца
    * Последний рабочий день месяца
    * Предновогодний выходной день

In [1]:
import datetime 

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from pandas.tseries.holiday import AbstractHolidayCalendar, Holiday, nearest_workday, EasterMonday
from pandas.tseries.offsets import DateOffset, Day

%matplotlib inline

In [16]:
df = pd.read_csv('data-calendar.csv')
df.tail()

,Год/Месяц,Январь,Февраль,Март,Апрель,Май,Июнь,Июль,Август,Сентябрь,Октябрь,Ноябрь,Декабрь,Всего рабочих дней,Всего праздничных и выходных дней,Количество рабочих часов при 40-часовой рабочей неделе,Количество рабочих часов при 36-часовой рабочей неделе,Количество рабочих часов при 24-часовой рабочей неделе
22,2021,"1,2,3,4,5,6,7,8,9,10,16,17,23,24,30,31","6,7,13,14,20,21,22*,23,27,28","6,7,8*,13,14,20,21,27,28","3,4,10,11,17,18,24,25,30*","1,2,3+,8,9,10+,15,16,22,23,29,30","5,6,11*,12,13,14+,19,20,26,27","3,4,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29","4,5,11,12,18,19,25,26","2,3,9,10,16,17,23,24,30,31","3*,4,6,7,13,14,20,21,27,28","4,5,11,12,18,19,25,26,31*",249,116,1987,1787.8,1190.2
23,2022,"1,2,3,4,5,6,7,8,9,15,16,22,23,29,30","5,6,12,13,19,20,22*,23,26,27","5,6,7*,8,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30","1,2+,7,8,9,14,15,21,22,28,29","4,5,11,12,13+,18,19,25,26","2,3,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","3,4,10,11,17,18,24,25","1,2,8,9,15,16,22,23,29,30","3*,4,5,6,12,13,19,20,26,27","3,4,10,11,17,18,24,25,31",249,116,1989,1789.8,1192.2
24,2023,"1,2,3,4,5,6,7,8,14,15,21,22,28,29","4,5,11,12,18,19,22*,23,25,26","4,5,7*,8,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","1,6,7,8*,9,13,14,20,21,27,28","3,4,10,11,12,17,18,24,25","1,2,8,9,15,16,22,23,29,30","5,6,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30","1,7,8,14,15,21,22,28,29","3*,4,5,6+,11,12,18,19,25,26","2,3,9,10,16,17,23,24,30,31",249,116,1988,1788.8,1191.6
25,2024,"1,2,3,4,5,6,7,8,13,14,20,21,27,28","3,4,10,11,17,18,22*,23,24,25","2,3,7*,8,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28,30*","1,4,5,8*,9,11,12,18,19,25,26","1,2,8,9,11*,12,15,16,22,23,29,30","6,7,13,14,20,21,27,28","3,4,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29","5,6,12,13,19,20,26,27","2,3,4,9,10,16,17,23,24,30","1,7,8,14,15,21,22,28,29,31*",250,116,1994,1794.0,1194.0
26,2025,"1,2,3,4,5,6,7,8,11,12,18,19,25,26","1,2,8,9,15,16,22,23,24+","1,2,7*,8,9,10+,15,16,22,23,29,30","5,6,12,13,19,20,26,27,30*","1,3,4,8*,9,10,11,17,18,24,25,31","1,7,8,11*,12,14,15,21,22,28,29","5,6,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","4,5,11,12,18,19,25,26","1,2,3*,4,8,9,15,16,22,23,29,30","6,7,13,14,20,21,27,28,31*",249,116,1986,1786.8,1189.2

In [17]:
#делаем список дат для итогового DF
a =pd.DataFrame()
a = pd.date_range('1999-1-1', periods=9862, name='Date', freq='D',)
#проверяем что последний период правильный
a[-1]

Timestamp('2025-12-31 00:00:00', freq='D')

In [18]:
a

DatetimeIndex(['1999-01-01', '1999-01-02', '1999-01-03', '1999-01-04',
               '1999-01-05', '1999-01-06', '1999-01-07', '1999-01-08',
               '1999-01-09', '1999-01-10',
               ...
               '2025-12-22', '2025-12-23', '2025-12-24', '2025-12-25',
               '2025-12-26', '2025-12-27', '2025-12-28', '2025-12-29',
               '2025-12-30', '2025-12-31'],
              dtype='datetime64[ns]', name='Date', length=9862, freq='D')

In [22]:
#формируем новый датафрейм
events= pd.DataFrame(a).set_index('Date')

In [24]:
events['выходной']=events['праздник']=events['предпраздничный рабочий день']=0
events['последний день месяца']=events['последний рабочий день месяца']=events['Предновогодний выходной день']=0

In [25]:
month =["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"]
week = ["пн","вт","ср","чт","пт","сб","вс"]
holidays = ['01-01-','07-01-','23-02-','08-03-','01-05-','12-06-','04-11-']

In [26]:
for i in range(0,7):
    events[str(week[i])]=(a.weekday==i).astype(np.int8)
for i in range(0,12):
    events[str(month[i])]=(a.month==i+1).astype(np.int8)

In [28]:
events

,выходной,праздник,предпраздничный рабочий день,последний день месяца,последний рабочий день месяца,Предновогодний выходной день,пн,вт,ср,чт,...,Март,Апрель,Май,Июнь,Июль,Август,Сентябрь,Октябрь,Ноябрь,Декабрь
Date,,,,,,,,,,,,,,,,,,,,,
1999-01-01,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1999-01-02,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1999-01-03,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1999-01-04,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1999-01-05,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2025-12-28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2025-12-29,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2025-12-30,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2025-12-31,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1

### Упражнение 2

* Для временного ряда курса акций Сбербанка на основе производственного календаря России сформируйте DataFrame признаков:
    * Лаговые переменные рабочих дней с глубинами: 1, 3, 5
    * Скользящие статистики `['mean', 'median', 'max', 'min', 'std'] ` с окнами 1, 3, 5 сгрупированные по дням недели
    * Статистики `['mean', 'median', 'max', 'min', 'std'] ` в расширяющемся окне сгруппированные по рабочим, праздничным и предпраздничным дням

In [34]:
ts = pd.read_csv('sber_stocks.csv', usecols=['CLOSE', 'TRADEDATE'], index_col='TRADEDATE', parse_dates=True)
ts = ts.CLOSE

In [35]:
tsd=ts.resample('1D').asfreq()

In [40]:
median=[]
print('Скользящая. Группировка по дням недели.')
for i in range(1,6,2):
    print('Окно =',i,'\n', ts.rolling(window=i).mean().groupby(ts.index.weekday).describe(percentiles = median))

Скользящая. Группировка по дням недели.
Окно = 1
            count        mean        std     min      50%     max
TRADEDATE
0          335.0  145.460716  62.585738   54.51  139.450  279.97
1          342.0  145.187135  62.201611   53.50  140.160  278.21
2          343.0  146.021662  62.164953   55.00  139.400  279.20
3          344.0  146.393837  62.047727   58.70  141.375  277.49
4          344.0  146.949942  61.965509   57.13  144.675  274.60
5            4.0  181.522500  55.146865  102.39  199.450  224.80
Окно = 3
            count        mean        std         min         50%         max
TRADEDATE
0          334.0  145.624062  62.561742   55.260000  138.888333  278.886667
1          341.0  145.143500  62.040534   55.513333  139.113333  278.556667
2          343.0  145.756638  61.948556   55.866667  139.073333  276.860000
3          344.0  146.266860  62.004002   55.900000  141.781667  275.203333
4          344.0  147.039109  62.097877   56.943333  143.238333  274.210000
5            4.0  181.146667  54.937231  102.196667  199.626667  223.136667
Окно = 5
            count        mean        std      min      50%      max
TRADEDATE
0          334.0  145.594359  62.577138   55.868  138.649  275.122
1          341.0  145.155302  62.037627   56.048  139.010  276.418
2          342.0  145.800181  61.857588   58.390  139.128  277.454
3          343.0  146.199726  61.854494   57.548  143.854  276.614
4          344.0  146.902052  62.039876   56.686  144.112  275.716
5            4.0  180.654000  55.869687  100.460  199.792  222.572